# Text Mining

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('per.csv', encoding='utf8')
# encoding :: این پارت زمانی استفاده میشود که فایل ما فارسی است
data.head()

NewsID                                              Title  \
0  843656  \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1  837144  \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2  436862  \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3  227781  \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4  174187  \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   

                                                Body         Date       Time  \
0  \nوزير علوم در جمع استادان نمونه كشور گفت: از ...  \n138/5//09  \n0:9::18   
1  \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...  \n138/5//09  \n1:4::11   
2  \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...  \n138/3//07  \n1:0::03   
3                                                 \n  \n138/2//02  \n1:3::42   
4  \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...  \n138/1//08  \n1:1::49   

             Category  Category2  
0           \nآموزشي-   \nآموزشي  
1           \nآموزشي-   \nآموزشي  
2           \nآموزشي-   \nآموزشي  
3  \nاجتماعي-خانواده-  \nاجتماعي  
4           \nآموزشي-   \nآموزشي

In [4]:
# stopwords :: کلماتی که از نظر معنای معنای خاصی ندارند و در یادگیری کمکی به ما نمیکنند
with open('stopwords.txt', encoding='utf8') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '')  for line in stopwords]
stopwords

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '...',
 '....',
 '/',
 ':',
 '<',
 '=',
 '>',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'ء',
 'آاو و و و',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسانی',
 'آسيب پذيرند',
 'آسیب',
 'آسیب پذیرند',
 'آشكارا',
 'آشنايند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن ها',
 'آن گاه',
 'آنان',
 'آناني',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنكه',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان كه',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهاي',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آيا',
 'آيد',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'ابدا',
 'ابلهانه',
 'ات',
 'اتفاقا',
 'اثر',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احياناً',
 'احیانا',
 'احیاناً',
 'اخ',
 'اختصارا',

In [5]:
# pip install nltk hazm
# nltk : natural language toolkit
# hazm : ...for Persian Language
# %pip install nltk hazm

In [6]:
import nltk 
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Sina\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
stopwords

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '...',
 '....',
 '/',
 ':',
 '<',
 '=',
 '>',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'ء',
 'آاو و و و',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسانی',
 'آسيب پذيرند',
 'آسیب',
 'آسیب پذیرند',
 'آشكارا',
 'آشنايند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن ها',
 'آن گاه',
 'آنان',
 'آناني',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنكه',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان كه',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهاي',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آيا',
 'آيد',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'ابدا',
 'ابلهانه',
 'ات',
 'اتفاقا',
 'اثر',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احياناً',
 'احیانا',
 'احیاناً',
 'اخ',
 'اختصارا',

In [8]:
import hazm
stemmer = hazm.Stemmer()

In [9]:
stemmer.stem('خانه هایشان')

'خانه '

In [10]:
from hazm import word_tokenize

In [11]:
# make data fram with two part :: data(title + body) and category
dataset = pd.DataFrame(columns=('title_body', 'category'))
for index , row in data.iterrows():
    # title and body
    title_body = row['Title'] + ' ' + row['Body']
    # tokenize all data
    title_body_tokenized = word_tokenize(title_body)
    # delete stopwords
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    # save data in datafram with category
    title_body_tokenized_filtered_stemed = [stemmer.stem(w) for w in title_body_tokenized_filtered]

    dataset.loc[index] = {
        'title_body' : ' '.join(title_body_tokenized_filtered_stemed),
        'category' : row['Category2'].replace('\n', ' ')
    }

In [12]:
dataset.head()

title_body  category
0  وزير علو درجمع استاد نمونه سن بازنشستگي استاد ...    آموزشي
1  گردهمايي دانش‌آموختگ موسسه آموز عالي سوره برگز...    آموزشي
2  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ن...    آموزشي
3  هماي يكروزه آسيب مفهو روابط عمومي بابلسر برگزا...   اجتماعي
4  وضعي اقتصادي تحصيل والدين مهمترين عوامل موفقي ...    آموزشي

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
vectorize = TfidfVectorizer()
vectorize.fit(dataset['title_body'])

TfidfVectorizer()

In [15]:
import pickle
with open('News.jsdh', 'wb') as f:
    pickle.dump(vectorize, f)

In [16]:
X = vectorize.transform(dataset['title_body'])
X

<10999x60555 sparse matrix of type '<class 'numpy.float64'>'
	with 1556085 stored elements in Compressed Sparse Row format>

In [17]:
from sklearn.preprocessing import LabelEncoder


In [18]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [19]:
le.classes_

array([' آموزشي', ' اجتماعي', ' اقتصادي', ' بهداشتي', ' تاريخي', ' سياسي',
       ' علمي', ' فرهنگي', ' فقه و حقوق', ' مذهبي', ' ورزشي'],
      dtype=object)

In [29]:
with open('Leabel.jsdh', 'wb') as f:
    pickle.dump(le, f)

In [20]:
import numpy as np
np.unique(dataset['category'])

array([' آموزشي', ' اجتماعي', ' اقتصادي', ' بهداشتي', ' تاريخي', ' سياسي',
       ' علمي', ' فرهنگي', ' فقه و حقوق', ' مذهبي', ' ورزشي'],
      dtype=object)

In [21]:
print(np.shape(X) + np.shape(y))

(10999, 60555, 10999)


In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train, y_test = train_test_split(X, y)

In [23]:
from sklearn import svm


In [24]:
svmc = svm.SVC()
svmc.fit(X_train, y_train)

SVC()

In [30]:
with open('svc.jsdh', 'wb') as f:
    pickle.dump(svmc, f)

In [25]:
svmc.score(X_test, y_test)

0.8349090909090909

In [26]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svmc.predict(X_test)

In [27]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.90      0.84      0.87       293
           1       0.66      0.61      0.63       261
           2       0.81      0.79      0.80       260
           3       0.93      0.82      0.87       268
           4       0.89      0.90      0.90       265
           5       0.72      0.80      0.76       223
           6       0.71      0.82      0.76       221
           7       0.88      0.81      0.84       246
           8       0.83      0.88      0.85       229
           9       0.90      0.95      0.92       244
          10       0.96      0.97      0.96       240

    accuracy                           0.83      2750
   macro avg       0.83      0.84      0.83      2750
weighted avg       0.84      0.83      0.84      2750



In [28]:
print(confusion_matrix(y_pred, y_test))

[[246  12   1   2   3   4  21   0   3   0   1]
 [  7 159  30   4   6  10   8   9  10  13   5]
 [  0  22 206   2   0  11   6   3   8   2   0]
 [ 10   5   1 220   0   4  24   1   1   2   0]
 [  0   6   1   0 239  11   0   2   5   1   0]
 [  0   7   8   1  11 178   1   2   9   3   3]
 [  7   8   5   6   1   4 182   5   2   0   1]
 [  2  16   3   0   5   4  10 200   1   4   1]
 [  0   3   0   1   1  19   1   3 201   0   0]
 [  0   4   0   0   2   3   0   2   2 231   0]
 [  1   0   0   0   0   0   4   1   0   0 234]]
